#!/usr/bin/env bash
# Installs nginx and sets up a custom "Hello World!" homepage

# Install nginx
apt-get update -y
apt-get install nginx -y

# Set custom HTML content
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Start nginx (without using systemctl)
service nginx start

