#!/bin/bash
# Update package lists
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create a simple index.html that displays Hello World!
echo "Hello World!" > /var/www/html/index.html

# Ensure Nginx is configured to listen on port 80 (this is default)
# Start Nginx using service
service nginx start

# Ensure the server responds with a 200 OK on root
curl -sI localhost | head -n 1




























































